# Generated by Django 4.2.3 on 2024-02-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='staff',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
