# Generated by Django 4.2.3 on 2024-02-20 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='warehouse',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='feed.warehouse'),
        ),
    ]
