# Generated by Django 4.2.3 on 2024-02-20 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_alter_staff_name_alter_staff_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='feed.warehouse'),
        ),
    ]
